### ISSUE TITLE
Rounding with same value, different factor

### ISSUE THREAD

**Issue by petermorlion** [petermorlion/RedStar.Amounts#1]
The following units are of equal value:

amountA : RawValue=27.5, Unit.Factor=10
amountB : RawValue=1.375, Unit.Factor=0.5

But:
AmountMath.Round(amountA, 1) = 27.5
AmountMath.Round(amountB, 1) = 1.4

Now change the Unit.Factor to 1, and you get:
amountA = 2.75
amountB = 2.8

Round should always check the unit (ie convert first)

**Comment by uncle-buzz** [comment]
This not really an issue, round is about representation, not precision, you define how much decimals you want to render. It changes the precision, but  it's different. If you want to keep same value even after conversion, you need to keep same precision.
Precision is like rounding with an amount, if units are friendly (factor 10) then you don't see difference between rounding and precision, but if you set the precision at 1 mbar to a pressure with PSI unit, you will keep many decimals.
If you want to compare 2 amounts, you need to use same precision, in your example, rounding with different units won't keep same precision, so you see different results.

> 100 psi = 6.8476 bar
> 5.525 bar = 72.518869 psi

```
round(100, 1) = 100 // 1 decimal, precision = 0.1 psi, same value
round (6.8476, 1) = 6.8 // 1 decimal, precision = 0.1 bar, different value
round(5.525, 1) = 5.5 // 1 decimal, precision = 0.1 bar
round (72.518869, 1) = 72.5 // 1 decimal, precision = 0.1 psi
```
so converting 5.5 bar to psi could not be equal to 72.5 psi.

It's something we have to be aware, but it's not an issue.

You could try to add a method to "round" an amount with an amount (5.525 bar round at 100 mbar => 5.5 bar) but conversion with factor different than integer could make trouble for comparison since it will introduce new imprecision (72.518869 psi round at 100 mbar => 5500 mbar if you convert 1st amount to mbar before rounding, 72.518869 psi round at 100 mbar =>71.06862 psi if you convert 2nd amount to psi)
1st case could be useful, if we assert than unit of 2nd amount is our target, converting then rounding will give us the attended result.

**Comment by petermorlion** [comment]
Could we conclude that rounding is something you should only be doing when you have some final result you want to display to the user? Not something to do with values that you still will use in calculations? Then we can should leave it as it is?

**Comment by uncle-buzz** [comment]
To my mind, rounding with an integer is about formating a value for displaying purpose, so no calculation should be donne after rounding (why loosing precision before doing more calculation ?)

**Comment by petermorlion** [comment]
Agreed. Closing. Thanks for your feedback!
